version: '3'
services:
    api:
        container_name: api
        build: .
        ports:
            - '9001:9001'
        volumes:
            - .:/app
        links:
            - mongo
    mongo:
        image: mongo:latest
        container_name: mongo
        ports:
            - '80:80'
        environment:
            MONGO_INITDB_DATABASE: image-repository-api
        volumes:
            - data-volume:/data/db
volumes:
    data-volume:
